name: archetype-warfare
services:
  nodejs:
    container_name: back-aw
    build:
      dockerfile: ./docker/Dockerfile.dev
    working_dir: /usr/src/
    env_file:
      - .env
    environment:
      - DATABASE_HOST=database
    volumes:
      - ./config:/usr/src/config
      - ./database:/usr/src/database
      - ./public:/usr/src/public
      - ./src:/usr/src/src
    networks:
      - network-project-aw
    ports:
      - '8889:1337'
  database:
    container_name: database-aw
    image: postgres:18
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: aw
    volumes:
      - pgdata:/var/lib/postgresql
      - ./docker-init:/docker-entrypoint-initdb.d
      - ./config/scripts:/scripts
    networks:
      - network-project-aw
    ports:
      - '8899:5432'

networks:
  network-project-aw:
    name: network-project-aw

volumes:
  pgdata:
