#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Run our validation script
node "$(dirname "$0")/scripts/validate-commit.js" "$1"

# If validation succeeds, run commitlint
if [ $? -eq 0 ]; then
  npx --no -- commitlint --edit "$1"
fi 